services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    name: postgres-data